#!/bin/bash

cd ~/rc3sync
for i in $(ls -1 | grep -v -e '^synced'); do
  # echo $i
  rc3sync.py $i

  if [ $? -eq 0 ]
  then
    echo "Success: copy successful."
    mv $i synced-$i
  else
    echo "Failure:" >&2
  fi
done